### ISSUE TITLE
Order of solutions does not follow order of questions

### ISSUE THREAD

**Issue by benjimelito** [ga-wdi-boston/js-reference-types-diagnostic#229]
I noticed that the solution code for question 2 relies on the solution code for question 4, and as a result question 4 is placed above question 2 in the diagnostic.md solution. I feel like either the order of the questions should be changed, or the solution for question 2 should not rely on the solution for question 4.

**Comment by gaand** [comment]
No.  This is intended as is.  It shows that one answer, the more complicated one, also resolves an easier question.
