### ISSUE TITLE
Questions are out of order

### ISSUE THREAD

**Issue by joaufi** [ga-wdi-boston/js-reference-types-diagnostic#98]
The questions for the diagnostic solution are out of order

**Comment by gaand** [comment]
I disagree.  Did you read the solution carefully?

**Comment by joaufi** [comment]
After re-reading the code, and taking into account the top comment 'Reuse functions wherever possible', I see now why the solutions have the functions in the order they have them. uniqueWords uses wordFrequencies to build it's array, so that is correct. Thank you for the learning opportunity!
